configuration: &accounts/configuration
  connection_info:
    database_url:
      from_env: HASURA_GRAPHQL_ACCOUNTS_URL
    pool_settings:
      retries: 1
      idle_timeout: 180
      max_connections: 50
